apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: '{{.Release.Name}}'
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{.Release.Name}}'
  namespace: '{{.Values.namespace}}'
spec:
  selector:
    matchLabels:
      k8s-app: '{{.Release.Name}}'
  replicas: 1
  template:
    metadata:
      name: '{{.Release.Name}}'
      labels:
        k8s-app: '{{.Release.Name}}'
    spec:
      volumes:
      - name: smp-peppol-setup
        hostPath:
          path: /data/phoss-smp-setup
      containers:
      - name: '{{.Release.Name}}'
        image: {{.Values.smp.image }}
        volumeMounts:
        - name: smp-peppol-setup
          mountPath: /setup
        ports:
        - containerPort: 80
        env:
        - name: JAVA_OPTS
          value: '{{.Values.smp.env.javaopts}}'
        - name: CONTEXT_NAME
          value: {{.Values.smp.contextName}}
        resources:
          requests:
            cpu: "0.3"
            memory: 512Mi
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
      - name: smp-peppol-setup
        hostPath:
          path: /data/phoss-smp-setup
      restartPolicy: Always
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
