{{- if .Values.jmx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name}}-jmx-http
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}-jmx-http'
  name: {{.Release.Name}}-jmx-http
  namespace: '{{.Values.namespace}}'
spec:
  ports:
  - name: http
    port: 8161
    protocol: TCP
    targetPort: 8161
  selector:
    app: {{.Release.Name}}-jmx
  type: 'NodePort'
{{- end }}
