{{- if .Values.cleanIn.enabled -}}
#apiVersion: batch/v1
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{.Release.Name}}-clean-in
  namespace: '{{.Values.namespace}}'
spec:
  schedule: '{{.Values.cleanIn.schedule}}'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{.Release.Name}}-clean-in
            image: {{.Values.cleanIn.image}}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never
{{- end }}
