{{- if .Values.cleanIn.enabled -}}
#apiVersion: batch/v1
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{.Release.Name}}-clean-in
  namespace: '{{.Values.namespace}}'
spec:
  schedule: '{{.Values.cleanIn.schedule}}'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: {{.Release.Name}}-clean-in
            image: {{.Values.cleanIn.image}}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; ls /data/IN/ -l; rmdir /data/IN/* || echo 'Surpressed non-0 exit code'
            volumeMounts:
            - mountPath: /data
              name: domibus-fs
              subPath: dynconcepttestparty0{{.Values.partyIndex}}gw
          volumes:
          - name: domibus-fs
            hostPath:
              path: /data/fs-plugin
{{- end }}
