apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name}}
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: {{.Release.Name}}
  namespace: '{{.Values.namespace}}'
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{.Release.Name}}
  type: '{{.Values.dtx.serviceType}}'
