apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: '{{.Release.Name}}'
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{.Release.Name}}'
  namespace: '{{.Values.namespace}}'
spec:
  selector:
    matchLabels:
      app: '{{.Release.Name}}'
  strategy:
    type: '{{.Values.dtx.deploymentStrategy}}'
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}'
    spec:
      restartPolicy: '{{.Values.dtx.restartPolicy}}'
      containers:
      - env:
        - name: DOMIBUS_HOME_OVERWRITE
          value: '/home/overwrite/*'

        - name: MERGE_DOMIBUS_PROPERTIES_ENV_PREFIX
          value: 'DOMIBUS_PROPERTY_'

        - name: DOMIBUS_PROPERTY_domibus_UI_title_name
          value: '{{.Values.partyName}} Domibus'
          
        - name: DOMIBUS_PROPERTY_DOMIBUS_SECURITY_KEYSTORE_LOCATION
          value: '{{.Values.dtx.env.keystorelocation}}'
        - name: DOMIBUS_PROPERTY_DOMIBUS_SECURITY_TRUSTSTORE_LOCATION
          value: '{{.Values.dtx.env.truststorelocation}}'
        - name: DOMIBUS_PROPERTY_DOMIBUS_SECURITY_KEY_PRIVATE_ALIAS
          value: 'dynconcepttestparty0{{.Values.partyIndex}}gw'
        - name: DOMIBUS_PROPERTY_DOMIBUS_SECURITY_KEY_PRIVATE_PASSWORD
          value: '{{.Values.dtx.env.keypassword}}'
        - name: DOMIBUS_PROPERTY_domibus_database_schema
          value: 'domibus{{.Values.partyIndex}}'
        - name: DOMIBUS_PROPERTY_DOMIBUS_DATABASE_SERVERNAME
          value: '{{.Values.dtx.env.databasehost}}'
        - name: DOMIBUS_PROPERTY_DOMIBUS_DATABASE_PORT
          value: '{{.Values.dtx.env.databaseport}}'
        - name: DOMIBUS_PROPERTY_DOMIBUS_DATASOURCE_USER
          value: 'domibus{{.Values.partyIndex}}dbuser'
        - name: DOMIBUS_PROPERTY_DOMIBUS_DATASOURCE_PASSWORD
          value: 'domibus{{.Values.partyIndex}}dbuser'
        - name: DOMIBUS_PROPERTY_DOMIBUS_DATASOURCE_XA_PROPERTY_USER
          value: 'domibus{{.Values.partyIndex}}dbuser'
        - name: DOMIBUS_PROPERTY_DOMIBUS_DATASOURCE_XA_PROPERTY_PASSWORD
          value: 'domibus{{.Values.partyIndex}}dbuser'
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_BROKER_HOST
          value: '{{.Values.dtx.env.activemqhost}}'
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_BROKERNAME
          value: "localhost"
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_USERNAME
          value: '{{.Values.dtx.env.activemqusername}}'
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_PASSWORD
          value: '{{.Values.dtx.env.activemqpassword}}'
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_CONNECTORPORT
          value: "1199"
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_RMISERVERPORT
          value: "1200"
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_TRANSPORTCONNECTOR_URI
          value: "tcp://localhost:61616?jms.watchTopicAdvisories=false"
        - name: DOMIBUS_PROPERTY_DOMIBUS_MSH_RETRY_CRON
          value: '{{.Values.dtx.env.cron}}'
        - name: DOMIBUS_PROPERTY_DOMIBUS_PULL_RETRY_CRON
          value: '{{.Values.dtx.env.cron}}'
        - name: DOMIBUS_PROPERTY_DOMIBUS_SMLZONE
          value: '{{.Values.dtx.env.smlzone}}'
        - name: DOMIBUS_PROPERTY_DOMIBUS_DYNAMICDISCOVERY_USEDYNAMICDISCOVERY
          value: "true"
        - name: DOMIBUS_PROPERTY_DOMIBUS_DISPATCHER_TIMEOUT
          value: '{{.Values.dtx.env.domibus_dispatcher_timeout}}'

        - name: JAVA_OPTS
          value: '{{.Values.dtx.env.javaopts}}'

        - name: DATABASE_HOST
          value: '{{.Values.dtx.env.databasehost}}'
        - name: DATABASE_PORT
          value: '{{.Values.dtx.env.databaseport}}'
        - name: DATABASE_USERNAME
          value: 'domibus{{.Values.partyIndex}}dbuser'
        - name: DATABASE_PASSWORD
          value: 'domibus{{.Values.partyIndex}}dbuser'

        - name: DOMIBUS_PROPERTY_domibus_dynamicdiscovery_client_specification
          value: PEPPOL
        - name: DOMIBUS_PROPERTY_domibus_dynamicdiscovery_peppolclient_mode
          value: TEST
        - name: DOMIBUS_PROPERTY_domibus_dynamicdiscovery_partyid_type
          value: urn:fdc:peppol.eu:2017:identifiers:ap
        - name: DOMIBUS_PROPERTY_domibus_dynamicdiscovery_transportprofileas4
          value: peppol-transport-as4-v2_0
        - name: DOMIBUS_PROPERTY_domibus_attachment_storage_location
          value: /domibus/attachment

        - name: DOMIBUS_PROPERTY_domibus_auth_unsecureLoginAllowed
          value: "{{.Values.dtx.env.unsecureLoginAllowed}}"
          
        - name: DOMIBUS_PROPERTY_domibus_auth_fsPluginAuthOn
          value: "{{.Values.dtx.env.fsplugin_auth_fix}}"

        - name: DOMIBUS_PROPERTY_fsplugin_validation_endpoint
          value: "{{.Values.dtx.env.fsplugin_validation_endpoint}}"

        - name: MERGE_FS_PROPERTIES_ENV_PREFIX
          value: 'FS_PROPERTY_'
        - name: FS_PROPERTY_fsplugin_authentication_user
          value: "fsplugin"
        - name: FS_PROPERTY_fsplugin_authentication_password
          value: "Systest1_"

        - name: CONTEXT_NAME
          value: domibus{{.Values.partyIndex}}

        image: '{{.Values.all.imagePrefix}}{{.Values.dtx.image}}:{{.Values.dtx.imageTag}}'
        imagePullPolicy: '{{.Values.dtx.imagePullPolicy}}'
        name: '{{.Release.Name}}'
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/tomcat/domibus/keystores
          name: domibus-ks
          subPath: keystore_dynconcepttestparty0{{.Values.partyIndex}}gw
        - mountPath: /usr/local/tomcat/logs
          name: domibus-logs
          subPath: dynconcepttestparty0{{.Values.partyIndex}}gw-logs
        - mountPath: /home/domibus/fs_plugin_data/MAIN
          name: domibus-fs
          subPath: dynconcepttestparty0{{.Values.partyIndex}}gw
        - mountPath: /app/domibus-webapp/WEB-INF/classes/peppol_pki_local
          name: pki-local
        - mountPath: /home/overwrite
          name: overwrite-home
      imagePullSecrets:
      - name: {{ .Values.dtx.imagePullSecret }}    
      volumes:
      - name: domibus-ks
        hostPath:
          path: /data/keystores
      - name: domibus-logs
        hostPath:
          path: /data/logs
      - name: domibus-fs
        hostPath:
          path: /data/fs-plugin
      - name: pki-local
        hostPath:
          path: /data/keystores/peppol_pki_local
      - name: overwrite-home
        hostPath:
          path: /data/domibus-overwrite/domibus{{.Values.partyIndex}}
