{{- if .Values.jmx.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: '{{.Release.Name}}-jmx'
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}-jmx'
  name: '{{.Release.Name}}-jmx'
  namespace: '{{.Values.namespace}}'
spec:
  selector:
    matchLabels:
      app: '{{.Release.Name}}-jmx'
  strategy:
    type: '{{.Values.jmx.deploymentStrategy}}'
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-jmx'
    spec:
      restartPolicy: '{{.Values.jmx.restartPolicy}}'
      containers:
      - env:
        - name: ACTIVEMQ_NAME
          value: {{.Values.dtx.env.activemqhost}}
        - name: ACTIVEMQ_CONFIG_DEFAULTACCOUNT
          value: 'false' #IMPORTANT - for security reasons remove all default accounts
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: '{{.Values.dtx.env.activemqusername}}'
        - name: ACTIVEMQ_ADMIN_PASSWORD
          value: '{{.Values.dtx.env.activemqpassword}}'
        - name: ACTIVEMQ_ENABLED_SCHEDULER
          value: 'false' #IMPORTANT - scheduler already activated, do not set it to true, otherwise double attribute is set

        - name: MERGE_DOMIBUS_PROPERTIES_ENV_PREFIX
          value: 'DOMIBUS_PROPERTY_'

        - name: DOMIBUS_PROPERTY_ACTIVEMQ_BROKER_HOST
          value: '{{.Values.dtx.env.activemqhost}}'
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_BROKERNAME
          value: "{{.Values.dtx.env.activemqBrokerName}}"
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_USERNAME
          value: '{{.Values.dtx.env.activemqusername}}'
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_PASSWORD
          value: '{{.Values.dtx.env.activemqpassword}}'
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_CONNECTORPORT
          value: "1199"
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_RMISERVERPORT
          value: "1200"
        - name: DOMIBUS_PROPERTY_ACTIVEMQ_TRANSPORTCONNECTOR_URI
          value: "{{.Values.jmx.env.activemqtransport}}"
        - name: DOMIBUS_PROPERTY_activeMQ_console_context
          value: "{{.Values.jmx.env.consoleContext}}"
        

        - name: JAVA_OPTS
          value: '{{.Values.jmx.env.javaopts}}'

        image: '{{.Values.all.imagePrefix}}{{.Values.jmx.image}}:{{.Values.jmx.imageTag}}'
        imagePullPolicy: '{{.Values.jmx.imagePullPolicy}}'
        name: '{{.Release.Name}}-jmx'
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data/activemq
          name: activemq-data
        - mountPath: /var/log/activemq
          name: activemq-log
      imagePullSecrets:
      - name: {{ .Values.dtx.imagePullSecret }}
      volumes:
      - name: activemq-data
        hostPath:
          path: /data/activemq/domibus{{.Values.partyIndex}}/data
      - name: activemq-log
        hostPath:
          path: /data/activemq/domibus{{.Values.partyIndex}}/log
{{- end }}
