{{- if .Values.jmx.enabled -}}
{{- if .Values.jmx.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: '{{.Release.Name}}-jmx'
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - edelivery-test.trueservice.dk
    secretName: tls-secret
  rules:
      - host: edelivery-test.trueservice.dk
        http:
          paths:
          - path: '/{{.Values.jmx.env.consoleContext}}'
            backend:
              serviceName: '{{.Release.Name}}-jmx-http'
              servicePort: 8161
{{- end }}
{{- end }}
