apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: '{{.Release.Name}}'
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - edelivery-test.trueservice.dk
    secretName: tls-secret
  rules:
      - host: edelivery-test.trueservice.dk
        http:
          paths:
          - path: '/domibus{{.Values.partyIndex}}'
            backend:
              serviceName: '{{.Release.Name}}'
              servicePort: 8080
