namespace: default
all:
  imagePrefix:
tw:
  enabled: true
  deploymentStrategy: RollingUpdate
  serviceType: NodePort
  image: test-web-console
  imageTag: latest
  imagePullPolicy: IfNotPresent
  env:
    javaopts: -Xmx384m -XX:MaxMetaspaceSize=128m
    filesRoot: /data/fs
    githubClientId: FILL_clientId
    githubClientSecret: FILL_clientSecret
    keystoresRoot: /data/keystores
    filesDeploymentLogs: /data/deployment_logs
bind:
  restartPolicy: Always
  bind:
    image: cef-erst/smp-bind
    imagePullPolicy: IfNotPresent
    imageTag: 1.0.0
    rootpassword: b1ndPassRut
  serviceType: NodePort
