namespace: default
all:
  imagePrefix:
tw:
  enabled: true
  deploymentStrategy: RollingUpdate
  serviceType: NodePort
  image: test-web-console
  imageTag: latest
  imagePullPolicy: IfNotPresent
  env:
    javaopts: -Xmx384m -XX:MaxMetaspaceSize=128m -Dserver.servlet.context-path=/twc -Dserver.tomcat.accesslog.enabled=true
    filesRoot: /data/fs
    keystoresRoot: /data/keystores
    filesDeploymentLogs: /data/deployment_logs