server.tomcat.basedir=/tmp/.dcm-tomcat
app.integration.inbox-catalogue=/data/delis-cm/integration/inbox/catalogue
app.integration.inbox-order-response=/data/delis-cm/integration/inbox/orderresponse
app.integration.outbox-order=/data/delis-cm/integration/outbox/order
app.order.endpointGLN=5798009882783
