namespace: default
name: domibus
partyName: blue
partyIndex: 1
all:
  imagePrefix: cef-erst/
dtx:
  deploymentStrategy: RollingUpdate
  
  image: domibus-tomcat
  imagePullPolicy: IfNotPresent
  imageTag: latest
  imagePullSecret:
  
  restartPolicy: Always
  serviceType: NodePort
  env:
    activemqhost: localhost
    activemqpassword: changeit
    activemqusername: domibus
    activemqtransport: tcp://localhost:61616?jms.watchTopicAdvisories=false
    databasehost: 172.16.2.4
    databaseport: "3306"
    javaopts: -Xmx384m -XX:MaxMetaspaceSize=200m -Dmode.TEST.security.pki=/peppol_pki_local/pki_local.xml -Dlogging.level.org.apache.cxf=INFO
    keypassword: test123
    pmodeprovider: DynamicDiscoveryPModeProvider
    smlzone: smp.cef.contest.my
    cron: "0/30 * * * * ?"
    keystorelocation: "/usr/local/tomcat/domibus/keystores/keystore.jks"
    truststorelocation: "/usr/local/tomcat/domibus/keystores/truststore.jks"
    domibus_dispatcher_timeout: 30000
    unsecureLoginAllowed: 'true'
    fsplugin_validation_endpoint: https://edelivery-test.trueservice.dk:443/delis-web-admin/rest/open/receivercheck/
    domibus_alert_sender_smtp_user: ''
    domibus_alert_sender_smtp_password: ''

  envExt: []

jmx:
  enabled: false
  deploymentStrategy: RollingUpdate
  
  image: domibus-activemq
  imagePullPolicy: IfNotPresent
  imageTag: latest
  imagePullSecret:
  
  restartPolicy: Always
  serviceType: NodePort
  env:
    javaopts: -Xmx384m -XX:MaxMetaspaceSize=200m
