apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-delis-index
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - edelivery-test.trueservice.dk
    secretName: tls-secret
  rules:
      - host: edelivery-test.trueservice.dk
        http:
          paths:
          - path: /
            backend:
              serviceName: delis-index
              servicePort: 8080