coreDns:
  enabled: false
kubeControllerManager:
  service:
    selector:
      k8s-app: null
      component: kube-controller-manager
kubeEtcd:
  service:
    selector:
      k8s-app: null
      component: etcd
kubeScheduler:
  service:
    selector:
      k8s-app: null
      component: kube-scheduler

grafana:
  adminPassword: 'Systest1_'
  ingress:
    enabled: 'true'
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    tls:
    - hosts:
      - edelivery-test.trueservice.dk
      secretName: tls-secret
    hosts:
    - edelivery-test.trueservice.dk
    path: /grafana

  grafana.ini:
    server:
      root_url: '%(protocol)s://%(domain)s:%(http_port)s/grafana/' #See https://github.com/helm/charts/issues/6264
      serve_from_sub_path: 'true'

#root_url: %(protocol)s://%(domain)s:%(http_port)s/
#root_url: http://localhost:3000/grafana/

prometheus:
  additionalServiceMonitors:
  - name: delis-web-admin-monitor
    selector:
      matchLabels:
        app: delis-admin
    namespaceSelector:
      matchNames:
        - default
    endpoints:
      - targetPort: 8080
        interval: 10s
        path: /delis-web-admin/actuator/prometheus
