coreDns:
  enabled: false
kubeControllerManager:
  service:
    selector:
      k8s-app: null
      component: kube-controller-manager
kubeEtcd:
  service:
    selector:
      k8s-app: null
      component: etcd
kubeScheduler:
  service:
    selector:
      k8s-app: null
      component: kube-scheduler

grafana:
  adminPassword: 'Systest1_'
  ingress:
    enabled: 'true'
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    tls:
    - hosts:
      - edelivery-test.trueservice.dk
      secretName: tls-secret
    hosts:
    - edelivery-test.trueservice.dk
    path: /grafana

  grafana.ini:
    server:
      root_url: 'https://edelivery-test.trueservice.dk/grafana/' #To have correct link in invitation email
      serve_from_sub_path: 'true'
  persistence:
    enabled: true
    size: 200Mi

prometheus:
  additionalServiceMonitors:
  - name: delis-web-admin-monitor
    selector:
      matchLabels:
        app: delis-admin
    namespaceSelector:
      matchNames:
        - default
    endpoints:
      - targetPort: 8080
        interval: 10s
        path: /delis-web-admin/actuator/prometheus
  - name: delis-web-api-monitor
    selector:
      matchLabels:
        app: "delis-api"
    namespaceSelector:
      matchNames:
        - default
    endpoints:
      - targetPort: 8080
        interval: 20s
        path: /delis-web-api/actuator/prometheus
  - name: delis-sender-service-monitor
    selector:
      matchLabels:
        prometheus-app: delis-sender-service
    namespaceSelector:
      matchNames:
        - default
    endpoints:
      - port: http
        interval: 15s
        path: /delis-sender-service/actuator/prometheus
  - name: domibus-monitor
    selector:
      matchLabels:
        app: dt1
    namespaceSelector:
      matchNames:
        - default
    endpoints:
      - targetPort: 8080
        interval: 10s
        path: /domibus1/prometheus
