apiVersion: v1
kind: Service
metadata:
  labels:
    app: bind
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: bind
  namespace: '{{.Values.namespace}}'
spec:
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: '{{.Release.Name}}-bind'
  type: '{{.Values.bind.serviceType}}'
