apiVersion: v1
data:                   
  Corefile: |           
    cef.contest.my:53 {
          forward . 172.17.0.5
     }
    .:53 {              
        errors          
        health          
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream     
           fallthrough in-addr.arpa ip6.arpa            
        }
        prometheus :9153
        proxy . /etc/resolv.conf                        
        cache 30
        reload
    }
kind: ConfigMap         
metadata:               
  name: coredns         
  namespace: kube-system