apiVersion: v1
kind: Service
metadata:
  labels:
    app: delis-gui-static
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: delis-gui-static
  namespace: '{{.Values.namespace}}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: '{{.Release.Name}}-delis-gui-static'
  type: NodePort
