apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: '{{.Release.Name}}-delis-gui-static'
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: delis-gui-static
  namespace: '{{.Values.namespace}}'
spec:
  selector:
    matchLabels:
      app: '{{.Release.Name}}-delis-gui-static'
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-delis-gui-static'
    spec:
      containers:
      - image: 'delis-gui-static:0.0.3'
        imagePullPolicy: IfNotPresent
        name: delis-gui-static
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        terminationMessagePolicy: File
      restartPolicy: Always
