apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-web-console
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: test-web-console
  namespace: '{{.Values.namespace}}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: '{{.Release.Name}}-test-web-console'
  type: '{{.Values.tw.serviceType}}'
