apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: '{{.Release.Name}}-delis-web-admin'
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: delis-web-admin
  namespace: '{{.Values.namespace}}'
spec:
  selector:
    matchLabels:
      app: '{{.Release.Name}}-delis-web-admin'
  strategy:
    type: 'RollingUpdate'
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-delis-web-admin'
    spec:
      containers:
      - image: delis-web-admin:latest
        imagePullPolicy: IfNotPresent
        name: delis-web-admin
        env:
          - name: SERVER_SERVLET_CONTEXT-PATH
            value: /delis-web-admin
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://172.16.2.4:3306/delis?useSSL=false
        volumeMounts:
        - mountPath: /delis-resources
          name: delis-resources
        - mountPath: /delis
          name: delis-root
        - mountPath: /load/input1
          name: data-input1
        - mountPath: /load/input2
          name: data-input2
      volumes:
      - name: delis-resources
        hostPath:
          path: /data/delis-resources
      - name: delis-root
        hostPath:
          path: /data/delis-root
      - name: data-input1
        hostPath:
          path: /data/fs-plugin/dynconcepttestparty01gw/IN
      - name: data-input2
        hostPath:
          path: /data/fs-plugin/dynconcepttestparty02gw/IN
