{{- if .Values.delisAngular.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name}}-angular
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: {{.Release.Name}}-angular
  namespace: '{{.Values.namespace}}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: '{{.Release.Name}}-angular'
  type: 'NodePort'
{{- end }}