apiVersion: v1
kind: Service
metadata:
  labels:
    app: delis-web-admin
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: delis-web-admin
  namespace: '{{.Values.namespace}}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: '{{.Release.Name}}-delis-web-admin'
  type: 'NodePort'
