{{- if .Values.delisIngress.enabled -}}
{{- if .Values.delisIngress.metrics.protected -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: '{{.Values.namespace}}'
  name: {{.Release.Name}}-{{ .Values.delisIngress.metrics.secretName }}
  labels:
    app.kubernetes.io/name: {{.Release.Name}}
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'

type: Opaque
data:
  auth: '{{- .Files.Get .Values.delisIngress.metrics.secretLocalFile | b64enc -}}'
{{- end }}
{{- end }}
