# Copied from:
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: image - delis-validator

on:
  push:
    branches: 
      - 'dev'
    paths:
      - 'delis-validator/**'
#    tags:
#      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: delis-validator

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Build mvn Delis
        run: mvn --batch-mode install -DskipTests=true

      - name: Prepare docker folder
        run: rm -r -f ./docker && mkdir ./docker && cp ./delis-docker/delis-web/docker/Dockerfile ./docker && rm -r -f ./docker/app

      - name: Copy mvn jar and unpack
        run: unzip ./delis-validator/target/delis-validator-1.0.0.jar -d ./docker/app

      - name: Move delis jars to a separate folder for copy in own layer
        run: mkdir ./docker/app/delis && mv ./docker/app/BOOT-INF/lib/delis-*.jar ./docker/app/delis

      - name: Read VERSION file to environment
        run: |
          IMAGE_VERSION=$(cat ./delis-validator/VERSION)
          echo "IMAGE_VERSION=$IMAGE_VERSION"
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: delis-validator - build and push image
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          tags: |
            dladlk/delis-validator:${{ env.IMAGE_VERSION }}
            dladlk/delis-validator:latest
