# Copied from:
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: image - domibus-ws-sender

on:
  push:
    # branches: 
    #   - 'dev'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-domibus-ws-sender

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-domibus-ws-sender
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}          

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build mvn Delis
        run: mvn --batch-mode install -DskipTests=true

      - name: Build mvn Domibus Ws Sender
        run: mvn --batch-mode package -DskipTests=true --file ./delis-domibus-ws-sender/pom.xml

      - name: Prepare docker folder
        run: rm -r -f ./docker && mkdir ./docker && cp ./delis-docker/delis-web/docker/Dockerfile ./docker && rm -r -f ./docker/app

      - name: Copy mvn jar and unpack
        run: unzip ./delis-domibus-ws-sender/target/delis-domibus-ws-sender-0.0.1.jar -d ./docker/app

      - name: Move delis jars to a separate folder for copy in own layer
        run: mkdir ./docker/app/delis && mv ./docker/app/BOOT-INF/lib/delis-*.jar ./docker/app/delis

      - name: delis-domibus-ws-sender - build and push image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
